services:
  - type: web
    name: crud_nome_email
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi
    preDeployCommand: python manage.py migrate
