services:
  - type: web
    name: crud-nome-email
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi
    postDeployCommand: python manage.py migrate
